export let compInfo = {
  'appname': '公司名称',
  'email': '电子邮箱',
  'contact': '联系人姓名',
  'contacttel': '联系人固定电话',
  'contactphone': '联系人移动电话',
  'appstate': '企业状态',
  // 'checkstate': '审核状态',
  'checkstatename': '审核状态',
  'srvorders': '服务订单',
  'appvcode': '企业编号',
  'vendortype': '公司类型',
  'vendorsort': '供应商类型',
  'companytype': '企业类型',
  'ownertype': '营业执照上的公司类型',
  'country': '所属国家',
  'area': '所属地区',
  'province': '所属省份',
  'city': '所属城市',
  'ofregion': '行政区划',
  'registeraddr': '详细地址',
  'appways': '组成形式',
  'currency': '币种编号',
  'registerfund': '注册资本',
  'registerdate': '企业成立日期',
  'opstartdate': '营业期限（起始）',
  'openddate': '营业期限（截止）',
  'bizscope': '经营范围',
  'orgcode': '组织机构代码',
  'bizcode': '工商注册号',
  'postaddr': '邮寄地址',
  'postcode': '邮编',
  'taxcode': '税务登记号（国税）',
  'taxtype': '纳税人类型',
  'appuser': '平台账号',
  'appregdate': '平台注册日期',
  'appdescnote': '备注信息',
  'appcheckdate': '平台准入日期',
  'quafiles': '资质信息列表',
  'vmsorts': '主营类别',
  'appinfobills': '审核记录',
  'appinfochg': '信息变更记录'
}

export let payInfo = {
  'vmsortcode': '主营类别编号',
  'vmsortname': '主营类别名称',
  'subtypename': '标的类型',
  'costname': '收费档次',
  'money': '收费金额'
}

export let compInfo1 = {
  'compCount': {
    'appuser': '平台账号',
    'contact': '联系人姓名',
    'contactphone': '移动电话',
    'contacttel': '联系人固定电话',
    'email': '电子邮箱',
    'postcode': '邮编',
    'postaddr': '邮寄地址',
    'registeraddr': '详细地址',
    'appregdate': '平台注册日期',
    'appcheckdate': '首次准入时间',
    'checkstatename': '审核状态',
    // 'checkstate': '审核状态',
    'appstate': '企业状态'
  },
  'compMsg': {
    'appname': '公司名称',
    'vendortype': '公司类型',
    'companytype': '企业类型',
    'appvcode': '企业编号',
    'ownertype': '营业执照上的公司类型',
    'vendorsort': '供应商类型',
    'registerdate': '成立日期',
    'opstartdate': '营业期限（起始）',
    'openddate': '营业期限（截止）',
    'country': '所属国家',
    'area': '所属地区',
    'province': '所属省份',
    'city': '所属城市',
    'registerfund': '注册资本',
    'currency': '币种编号',
    'bizcode': '工商注册号',
    'orgcode': '组织机构代码',
    'appways': '组成形式',
    'taxcode': '税务登记号（国税）',
    'taxtype': '纳税人类型',
    'bizscope': '经营范围',
    'ofregion': '行政区划',
    'appinfochg': '信息变更记录',
    'appdescnote': '备注信息'
  },
  'quafiles': ['资质类型', '文件ID', '文件名称'],
  'vmsorts': ['标的类型', '主营类别'],
  'srvorders': ['申请人', '申请时间', '订单编号', '服务类型', '服务名称', '订单金额（元）', '支付状态', '服务开始时间', '服务结束时间', '订单状态', '是否开票', '发票邮寄地址'],
  'appinfobills': ['业务类型', '申请日期', '审批日期', '审批状态', '审批意见']
}

